export const MY_ACTIVITY_POST_WINDOW_OPEN = 'MY_ACTIVITY_POST_WINDOW_OPEN';
export const MY_ACTIVITY_POST_WINDOW_CLOSE = 'MY_ACTIVITY_POST_WINDOW_CLOSE';

export const GET_MY_ACTIVITY_START = 'GET_MY_ACTIVITY_START';
export const GET_MY_ACTIVITY_SUCCEED = 'GET_MY_ACTIVITY_SUCCEED';
export const GET_MY_ACTIVITY_FAILED = 'GET_MY_ACTIVITY_FAILED';
