export const MY_ACTIVITY_POST_WINDOW_OPEN = 'MY_ACTIVITY_POST_WINDOW_OPEN';
export const MY_ACTIVITY_POST_WINDOW_CLOSE = 'MY_ACTIVITY_POST_WINDOW_CLOSE';

export const RELOAD_MY_ACTIVITY_START = 'RELOAD_MY_ACTIVITY_START';

export const GET_MY_ACTIVITY_START = 'GET_MY_ACTIVITY_START';
export const GET_MY_ACTIVITY_SUCCEED = 'GET_MY_ACTIVITY_SUCCEED';
export const GET_MY_ACTIVITY_FAILED = 'GET_MY_ACTIVITY_FAILED';

export const POST_MY_ACTIVITY_START = 'POST_MY_ACTIVITY_START';
export const POST_MY_ACTIVITY_SUCCEED = 'POST_MY_ACTIVITY_SUCCEED';
export const POST_MY_ACTIVITY_FAILED = 'POST_MY_ACTIVITY_FAILED';

export const SHOW_MY_ACTIVITY_START = 'SHOW_MY_ACTIVITY_START';
export const SHOW_MY_ACTIVITY_SUCCEED = 'SHOW_MY_ACTIVITY_SUCCEED';
export const SHOW_MY_ACTIVITY_FAILED = 'SHOW_MY_ACTIVITY_FAILED';

export const EDIT_MY_ACTIVITY_START = 'EDIT_MY_ACTIVITY_START';
export const EDIT_MY_ACTIVITY_SUCCEED = 'EDIT_MY_ACTIVITY_SUCCEED';
export const EDIT_MY_ACTIVITY_FAILED = 'EDIT_MY_ACTIVITY_FAILED';

export const DELETE_MY_ACTIVITY_START = 'DELETE_MY_ACTIVITY_START';
export const DELETE_MY_ACTIVITY_SUCCEED = 'DELETE_MY_ACTIVITY_SUCCEED';
export const DELETE_MY_ACTIVITY_FAILED = 'DELETE_MY_ACTIVITY_FAILED';
