export const GET_DRAFT_START = 'GET_DRAFT_START';
export const GET_DRAFT_SUCCEED = 'GET_DRAFT_SUCCEED';
export const GET_DRAFT_FAILED = 'GET_DRAFT_FAILED';

export const REGIST_DRAFT_START = 'REGIST_DRAFT_START';
export const REGIST_DRAFT_SUCCEED = 'REGIST_DRAFT_SUCCEED';
export const REGIST_DRAFT_FAILED = 'REGIST_DRAFT_FAILED';
