export const GET_TOP_INFO_RELOAD = 'GET_TOP_INFO_RELOAD';
export const GET_TOP_INFO_START = 'GET_TOP_INFO_START';
export const GET_TOP_INFO_SUCCEED = 'GET_TOP_INFO_SUCCEED';
export const GET_TOP_INFO_FAILED = 'GET_TOP_INFO_FAILED';
